# Generated by Django 5.1.3 on 2025-08-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_statistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='is_active',
        ),
        migrations.AddField(
            model_name='statistic',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
