# Generated by Django 5.1.3 on 2025-08-29 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_department_created_by_statistic_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='vacancies/')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
