# Generated by Django 5.1.3 on 2026-01-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_tuitionfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('outcome_based', 'Outcome-Based'), ('industry_extension', 'Industry Extension')], default='outcome_based', max_length=30),
        ),
    ]
