# Generated by Django 5.1.3 on 2026-03-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_deanmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='deanmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='vacancies/'),
        ),
    ]
